# Generated by Django 4.2.10 on 2024-04-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='Business Email')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('route_types', models.CharField(choices=[('lead climbing', 'Lead climbing'), ('top rope', 'Top Rope'), ('bouldering', 'Bouldering'), ('crack climbing', 'Crack Climbing')], help_text='Select the route types offered by the gym', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('route_setter', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('date_added', models.DateField()),
                ('about', models.TextField(blank=True)),
                ('wall_num', models.IntegerField(blank=True)),
                ('gym', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='climber_app.gym')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
