# Generated by Django 4.2.10 on 2024-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='route_types',
        ),
        migrations.AddField(
            model_name='gym',
            name='bouldering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='crack_climbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='lead_climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='top_rope',
            field=models.BooleanField(default=False),
        ),
    ]
