# Generated by Django 4.2.10 on 2024-04-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0003_rename_lead_climb_gym_lead_climbing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
