# Generated by Django 4.2.10 on 2024-04-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0004_gym_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='gym',
            name='membership_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
