# Generated by Django 4.2.10 on 2024-04-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0006_route_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='type',
            new_name='route_type',
        ),
    ]
