# Generated by Django 4.2.10 on 2024-04-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0009_alter_route_route_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
    ]
