# Generated by Django 4.2.10 on 2024-04-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0014_gym_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gym_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Business Email'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='membership_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
