# Generated by Django 4.2.10 on 2024-04-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0015_gym_gym_image_alter_gym_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='gym_image',
        ),
        migrations.AddField(
            model_name='gym',
            name='gym_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
