# Generated by Django 4.2.10 on 2024-04-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber_app', '0016_remove_gym_gym_image_gym_gym_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='gym_file',
        ),
        migrations.AddField(
            model_name='gym',
            name='gym_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
